version: "3"
services:
  flask:
    build: .
    container_name: flask_server
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/var/www
    ports:
      - "8080:8080"
    command: gunicorn --workers=2 -b 0.0.0.0:8080 app:app
    networks:
      my-network:
        aliases:
          - flask_server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://flask:8080" ]
      interval: 2s
      timeout: 2s
      retries: 5

networks:
  my-network:
  flask:
    driver: bridge
